<?php

namespace Tests\Unit\Models;

use App\Libraries\enums\JenisKelamin;
use App\Models\memberModel;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;

/**
 * @internal
 */
final class memberModelTest extends CIUnitTestCase
{
    use DatabaseTestTrait;

    protected $migrate     = true;
    protected $migrateOnce = true;
    protected $refresh     = true;
    protected $namespace   = null;

    protected memberModel $model;

    protected function setUp(): void
    {
        parent::setUp();
        $this->model = new memberModel();
    }
    
    protected function tearDown(): void
    {
        parent::tearDown();
        $this->db->table('tb_member')->delete('1 = 1');
    }

    // =====================================================
    // HAPPY PATH TESTS - CREATE OPERATIONS
    // =====================================================

    public function testCreatememberSuccessfully(): void
    {
        $result = $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $this->assertTrue($result);
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $this->assertNotNull($member);
        $this->assertEquals('John Teacher', $member['nama_member']);
        $this->assertEquals(JenisKelamin::LAKI_LAKI->value, $member['jenis_kelamin']);
        $this->assertEquals('Jl. Pendidikan No. 1', $member['alamat']);
        $this->assertEquals('08123456789', $member['no_hp']);
        $this->assertNotEmpty($member['unique_code']);
    }

    public function testCreatememberWithRfid(): void
    {
        $result = $this->model->createmember(
            '1234567890123456',
            'Jane Teacher',
            JenisKelamin::PEREMPUAN->value,
            'Jl. Pendidikan No. 2',
            '08123456788',
            'RFID123456'
        );
        
        $this->assertTrue($result);
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $this->assertEquals('RFID123456', $member['rfid_code']);
    }

    public function testCreatememberGeneratesUniqueCode(): void
    {
        $result = $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        // Check unique_code format - should be generated by hash
        $this->assertNotEmpty($member['unique_code']);
        $this->assertIsString($member['unique_code']);
        $this->assertGreaterThan(40, strlen($member['unique_code'])); // SHA1 (40) + partial SHA1 (24) = 64
    }

    // =====================================================
    // HAPPY PATH TESTS - READ OPERATIONS
    // =====================================================

    public function testCekmemberByUniqueCode(): void
    {
        $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $result = $this->model->cekmember($member['unique_code']);
        
        $this->assertNotNull($result);
        $this->assertEquals('John Teacher', $result['nama_member']);
    }

    public function testCekmemberByRfidCode(): void
    {
        $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789',
            'RFID123456'
        );
        
        $result = $this->model->cekmember('RFID123456');
        
        $this->assertNotNull($result);
        $this->assertEquals('John Teacher', $result['nama_member']);
        $this->assertEquals('RFID123456', $result['rfid_code']);
    }

    public function testGetAllmember(): void
    {
        $this->model->createmember('1234567890123456', 'John Teacher', JenisKelamin::LAKI_LAKI->value, 'Jl. Test 1', '08123456789');
        $this->model->createmember('1234567890123457', 'Jane Teacher', JenisKelamin::PEREMPUAN->value, 'Jl. Test 2', '08123456788');
        
        $result = $this->model->getAllmember();
        
        $this->assertIsArray($result);
        $this->assertCount(2, $result);
    }

    public function testGetmemberById(): void
    {
        $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $result = $this->model->getmemberById($member['id_member']);
        
        $this->assertNotNull($result);
        $this->assertEquals('John Teacher', $result['nama_member']);
    }

    // =====================================================
    // HAPPY PATH TESTS - UPDATE OPERATIONS
    // =====================================================

    public function testUpdatemember(): void
    {
        $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $result = $this->model->updatemember(
            $member['id_member'],
            '1234567890123456',
            'John Updated',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Updated Address',
            '08123456780'
        );
        
        $this->assertTrue($result);
        
        $updatedmember = $this->model->getmemberById($member['id_member']);
        
        $this->assertEquals('John Updated', $updatedmember['nama_member']);
        $this->assertEquals('Jl. Updated Address', $updatedmember['alamat']);
        $this->assertEquals('08123456780', $updatedmember['no_hp']);
    }

    public function testUpdatememberWithRfid(): void
    {
        $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $result = $this->model->updatemember(
            $member['id_member'],
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789',
            'RFID789456'
        );
        
        $this->assertTrue($result);
        
        $updatedmember = $this->model->getmemberById($member['id_member']);
        
        $this->assertEquals('RFID789456', $updatedmember['rfid_code']);
    }

    // =====================================================
    // UNHAPPY PATH TESTS
    // =====================================================

    public function testCekmemberWithInvalidCode(): void
    {
        $result = $this->model->cekmember('invalid-code-999');
        
        $this->assertNull($result);
    }

    public function testGetmemberByIdWithInvalidId(): void
    {
        $result = $this->model->getmemberById(99999);
        
        $this->assertNull($result);
    }

    public function testGetAllmemberWhenEmpty(): void
    {
        $result = $this->model->getAllmember();
        
        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    // =====================================================
    // EDGE CASES
    // =====================================================

    public function testCreatememberGeneratesDifferentUniqueCodes(): void
    {
        $this->model->createmember('1234567890123456', 'John Teacher', JenisKelamin::LAKI_LAKI->value, 'Jl. Test 1', '08123456789');
        $this->model->createmember('1234567890123457', 'Jane Teacher', JenisKelamin::PEREMPUAN->value, 'Jl. Test 2', '08123456788');
        
        $member1 = $this->db->table('tb_member')->where('', '1234567890123456')->get()->getRowArray();
        $member2 = $this->db->table('tb_member')->where('', '1234567890123457')->get()->getRowArray();
        
        $this->assertNotEquals($member1['unique_code'], $member2['unique_code']);
    }

    public function testUpdatememberDoesNotChangeUniqueCode(): void
    {
        $this->model->createmember(
            '1234567890123456',
            'John Teacher',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Pendidikan No. 1',
            '08123456789'
        );
        
        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();
        
        $originalUniqueCode = $member['unique_code'];
        
        $this->model->updatemember(
            $member['id_member'],
            '1234567890123456',
            'John Updated',
            JenisKelamin::LAKI_LAKI->value,
            'Jl. Updated Address',
            '08123456780'
        );
        
        $updatedmember = $this->model->getmemberById($member['id_member']);
        
        $this->assertEquals($originalUniqueCode, $updatedmember['unique_code']);
    }

    public function testGetAllmemberOrderedByName(): void
    {
        $this->model->createmember('1234567890123456', 'Zack Teacher', JenisKelamin::LAKI_LAKI->value, 'Jl. Test 1', '08123456789');
        $this->model->createmember('1234567890123457', 'Alice Teacher', JenisKelamin::PEREMPUAN->value, 'Jl. Test 2', '08123456788');
        $this->model->createmember('1234567890123458', 'Bob Teacher', JenisKelamin::LAKI_LAKI->value, 'Jl. Test 3', '08123456787');
        
        $result = $this->model->getAllmember();
        
        $this->assertEquals('Alice Teacher', $result[0]['nama_member']);
        $this->assertEquals('Bob Teacher', $result[1]['nama_member']);
        $this->assertEquals('Zack Teacher', $result[2]['nama_member']);
    }

    public function testCekmemberReturnsFirstMatchForOrCondition(): void
    {
        // Test that cekmember works with either unique_code OR rfid_code
        $this->model->createmember('1234567890123456', 'John Teacher', JenisKelamin::LAKI_LAKI->value, 'Jl. Test', '08123456789', 'RFID123');
        
        $member = $this->db->table('tb_member')->where('', '1234567890123456')->get()->getRowArray();
        
        $resultByUniqueCode = $this->model->cekmember($member['unique_code']);
        $resultByRfid = $this->model->cekmember('RFID123');
        
        $this->assertNotNull($resultByUniqueCode);
        $this->assertNotNull($resultByRfid);
        $this->assertEquals($resultByUniqueCode['id_member'], $resultByRfid['id_member']);
    }

    public function testGenerateCSVObjectSuccessfully(): void
    {
        $csvContent = ",nama_member,jenis_kelamin,alamat,no_hp\n" .
                      "1234567890123456,member One,L,Jl. Test 1,08111111111\n" .
                      "9876543210987654,member Two,P,Jl. Test 2,08222222222\n";

        $tmpDir = FCPATH . 'uploads/tmp/';
        if (!is_dir($tmpDir)) {
            mkdir($tmpDir, 0777, true);
        }

        $tempFile = $tmpDir . 'test_member_' . uniqid() . '.csv';
        file_put_contents($tempFile, $csvContent);

        $result = $this->model->generateCSVObject($tempFile);

        $this->assertNotEmpty($result);
        $this->assertEquals(2, $result->numberOfItems);
        $this->assertNotEmpty($result->txtFileName);

        $txtFile = $tmpDir . $result->txtFileName;
        $this->assertFileExists($txtFile);

        @unlink($txtFile);
    }

    public function testGenerateCSVObjectWithBOM(): void
    {
        $csvContent = "\xEF\xBB\xBF,nama_member,jenis_kelamin,alamat,no_hp\n" .
                      "1234567890123456,member Test,L,Jl. Test,08111111111\n";

        $tmpDir = FCPATH . 'uploads/tmp/';
        if (!is_dir($tmpDir)) {
            mkdir($tmpDir, 0777, true);
        }

        $tempFile = $tmpDir . 'test_member_bom_' . uniqid() . '.csv';
        file_put_contents($tempFile, $csvContent);

        $result = $this->model->generateCSVObject($tempFile);

        $this->assertNotEmpty($result);
        $this->assertEquals(1, $result->numberOfItems);

        $txtFile = FCPATH . 'uploads/tmp/' . $result->txtFileName;
        @unlink($txtFile);
    }

    public function testImportCSVItemSuccessfully(): void
    {
        $testData = [
            [
                '' => '1234567890123456',
                'nama_member' => 'Imported member',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Import Test',
                'no_hp' => '08123456789'
            ]
        ];

        $tmpDir = FCPATH . 'uploads/tmp/';
        if (!is_dir($tmpDir)) {
            mkdir($tmpDir, 0777, true);
        }

        $txtFileName = 'test_' . uniqid() . '.txt';
        $txtFile = fopen($tmpDir . $txtFileName, 'w');
        fwrite($txtFile, serialize($testData));
        fclose($txtFile);

        $result = $this->model->importCSVItem($txtFileName, 1);

        $this->assertNotEmpty($result);
        $this->assertEquals('1234567890123456', $result['']);
        $this->assertEquals('Imported member', $result['nama_member']);
        $this->assertNotEmpty($result['unique_code']);

        $member = $this->db->table('tb_member')
            ->where('', '1234567890123456')
            ->get()
            ->getRowArray();

        $this->assertNotNull($member);
        $this->assertEquals('Imported member', $member['nama_member']);

        @unlink($tmpDir . $txtFileName);
    }

    public function testImportCSVItemWithMultipleRecords(): void
    {
        $testData = [
            [
                '' => '1111111111111111',
                'nama_member' => 'First member',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. First',
                'no_hp' => '08111111111'
            ],
            [
                '' => '2222222222222222',
                'nama_member' => 'Second member',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Second',
                'no_hp' => '08222222222'
            ]
        ];

        $tmpDir = FCPATH . 'uploads/tmp/';
        if (!is_dir($tmpDir)) {
            mkdir($tmpDir, 0777, true);
        }

        $txtFileName = 'test_multi_' . uniqid() . '.txt';
        $txtFile = fopen($tmpDir . $txtFileName, 'w');
        fwrite($txtFile, serialize($testData));
        fclose($txtFile);

        $result = $this->model->importCSVItem($txtFileName, 2);

        $this->assertNotEmpty($result);
        $this->assertEquals('2222222222222222', $result['']);
        $this->assertEquals('Second member', $result['nama_member']);

        @unlink($tmpDir . $txtFileName);
    }

    public function testGenerateCSVObjectWithEmptyFile(): void
    {
        $csvContent = ",nama_member,jenis_kelamin,alamat,no_hp\n";

        $tmpDir = FCPATH . 'uploads/tmp/';
        if (!is_dir($tmpDir)) {
            mkdir($tmpDir, 0777, true);
        }

        $tempFile = $tmpDir . 'test_empty_' . uniqid() . '.csv';
        file_put_contents($tempFile, $csvContent);

        $result = $this->model->generateCSVObject($tempFile);

        $this->assertFalse($result);
    }
}
